import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  useEffect(() => {
    console.log("index page did mount")
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello everyone!
        </h1>
        <nav>
          <Link href="/about">About</Link>
          <Link href='/terms-of-use'>Terms of use</Link>
        </nav>
      </main>  
    </div>
  )
}
